name: Build my gnutemps image and push to my registry

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  slack-start:
    uses: pgmac-net/pg-actions/.github/workflows/slack-notify-start.yml@main
    secrets: inherit

  build-n-push:
    needs: [slack-start]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set the image version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag macro.int.pgmac.net:5000/gnutemps:${{ inputs.tags || steps.vars.outputs.tag }}
      - name: Push to my internal registry
        if: github.ref == 'refs/heads/"master"'
        run: docker push macro.int.pgmac.net:5000/gnutemps:${{ inputs.tags || steps.vars.outputs.tag }}

  slack-end:
    if: always()
    needs: [slack-start, build-n-push]
    uses: pgmac-net/pg-actions/.github/workflows/slack-notify-end.yml@main
    with:
      ts: ${{ needs.slack-start.outputs.ts }}
      start: ${{ needs.slack-start.outputs.start }}
      startfmt: ${{ needs.slack-start.outputs.startfmt }}
      status: ${{ needs.build-n-push.result }}
    secrets: inherit
